enyo.depends(
	"source/PrintDialogString.js",
	"source/PrintManagerError.js",
	"source/PrintManagerService.js",
	"source/PrintJob.js",
	"source/ImagePrintJob.js",
	"source/DocumentPrintJob.js",
	"source/MessageBox.js",
	"source/ProgressPopup.js",
	"source/PrinterSelector.js",
	"source/MediaSizePicker.js",
	"source/MediaTypePicker.js",
	"source/PrintQualityPicker.js",
	"source/PrinterOptions.js",
	"source/PrinterAdder.js",
	"source/PrintDialog.js",
	"css/PrintDialog.css",
	"source/PrintMediaStyle.js"
);
